function [centers radiuses] = GetMovingRegions(Sp,CThreshold)
% Project: Dense Visual Odometry
% Function: GetMovingRegions
%
% Description:
%   Get the moving regions' location and scope.
%
% Example:
%   [centers radiuses] = GetMovingRegions(Sp,CThreshold)
%   
%   centers: Moving regions' centers represented by a group of x,y
%           coordinate
%   radiuses: Radius of moving regions. Each moving region is approximately
%           represented by a circle generated by its center and
%           corresponding redius
%   SP: The suspected points (above-mentioned white points)
%   CTreshold: An useful parameter used in the clustering method.
% NOTE: 
%
% Author: Ethan Zhou
% Email: cavatina@yeah.net
% Website: https://github.com/Ethan-Zhou/Dense-VO
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% log:
% 2014-05-27: Complete
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
[SNum SDim] = size(Sp);
d = pdist(Sp);
z = linkage(d,'average');
c = cluster(z,'Cutoff',CThreshold);

% 将元素数小于阈值的类取消，求出种类数
% 求数据的质心
% 求半径

k = max(c);
[L,C] = kmeans(Sp,k);
[centers radiuses] = GetRegionsInfo(Sp,L,C);